version: '3'

services:
  jenkins:
    image: jenkins-maven:latest
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - testnet
  
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    ports:
      - "8081:8081"
    networks:
      - testnet

volumes:
  jenkins_home:

networks:
  testnet: